"""Stage 3: chapters.norm.json -> cast.yaml via the local LLM.

Never overwrites an existing cast.yaml (the user edits it to assign voices);
use --force to regenerate. Two passes: per-chapter discovery, then a whole-book
alias merge. The LLM returns names only; no book text is rewritten.
"""

from __future__ import annotations

import yaml
from rich.progress import track

from ab.config import BookConfig, BookPaths
from ab.llm import Ollama, pack
from ab.log import note
from ab.models import ChapterList

_DISCOVER_SCHEMA = {
    "type": "object",
    "properties": {
        "characters": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "aliases": {"type": "array", "items": {"type": "string"}},
                    "description": {"type": "string"},
                },
                "required": ["name", "aliases", "description"],
            },
        }
    },
    "required": ["characters"],
}
_MERGE_SCHEMA = {
    "type": "object",
    "properties": {
        "groups": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "canonical": {"type": "string"},
                    "aliases": {"type": "array", "items": {"type": "string"}},
                    "description": {"type": "string"},
                },
                "required": ["canonical", "aliases", "description"],
            },
        }
    },
    "required": ["groups"],
}

_SYSTEM = {
    "en": "You analyse fiction for audiobook production. Answer only with JSON.",
    "zh": "你在为有声书制作分析小说。只用JSON回答。",
}
_DISCOVER = {
    "en": (
        "List every character who SPEAKS dialogue in this chapter. For each give the name "
        "as most commonly written, other names/titles used for the same person, and a short "
        "description (role, gender, age, manner of speaking). Do not include characters who "
        "are only mentioned.\n\n{text}"
    ),
    "zh": (
        "列出本章中所有说过话的角色。对每个角色给出最常用的名字、指同一人的其他称呼、"
        "以及简短描述（身份、性别、年龄、说话方式）。不要包含只被提及而没有说话的角色。\n\n{text}"
    ),
}
_MERGE = {
    "en": (
        "These character entries were collected chapter by chapter from one novel and may "
        "contain duplicates (same person under different names or titles). Merge entries that "
        "refer to the same person. Keep distinct people separate even if they share a surname. "
        "Choose the most common short name as canonical.\n\n{entries}"
    ),
    "zh": (
        "以下角色条目是从同一部小说逐章收集的，可能有重复（同一人物的不同称呼）。"
        "合并指同一人物的条目，不同的人物即使同姓也要分开。选择最常用的简称作为规范名。\n\n{entries}"
    ),
}


def run(paths: BookPaths, cfg: BookConfig, force: bool = False):
    if paths.cast.exists() and not force:
        return paths.cast
    lang = cfg.language
    llm = Ollama.from_config(cfg, log=paths.llm_log)
    book = ChapterList.model_validate_json(paths.chapters_norm.read_text(encoding="utf-8"))

    found: list[dict] = []
    budget = llm.window_budget(_DISCOVER[lang].format(text="") + _SYSTEM[lang])
    for ch in track(book.chapters, description="cast: discover"):
        # Windows of whole paragraphs sized to the context budget, not a fixed
        # character count: 12k Chinese characters is ~8k tokens, twice Ollama's
        # default window, and was being truncated silently.
        for window in pack(ch.paragraphs, budget):
            res = llm.json(_DISCOVER[lang].format(text="\n\n".join(window)),
                           _DISCOVER_SCHEMA, system=_SYSTEM[lang])
            found.extend(res.get("characters", []))

    # Cheap exact-name dedupe before asking the model to merge.
    by_name: dict[str, dict] = {}
    for c in found:
        n = c["name"].strip()
        if not n:
            continue
        e = by_name.setdefault(n, {"name": n, "aliases": set(), "description": c["description"]})
        e["aliases"].update(a.strip() for a in c.get("aliases", []) if a.strip() and a.strip() != n)
    entries = "\n".join(f"- {e['name']} (aka {', '.join(sorted(e['aliases'])) or '-'}): {e['description']}"
                        for e in by_name.values())
    merged = llm.json(_MERGE[lang].format(entries=entries), _MERGE_SCHEMA, system=_SYSTEM[lang])

    characters = {}
    for g in merged.get("groups", []):
        canon = g["canonical"].strip()
        if not canon:
            continue
        aliases = sorted({a.strip() for a in g.get("aliases", []) if a.strip() and a.strip() != canon})
        characters[canon] = {"aliases": aliases, "description": g.get("description", "").strip()}

    paths.cast.write_text(
        "# Generated by `ab cast`. Edit freely; assign voices in book.yaml under `voices:`.\n"
        + yaml.safe_dump({"characters": characters}, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )
    note(paths, f"cast: {len(characters)} characters -> {paths.cast}")
    llm.unload()
    return paths.cast
